- name: change passwd
  hosts: all
  sudo: yes
  tasks:
  - name: change passwd 
    user:
      name: "{{ item.username }}"
      comment: hadoop service account
      password: "{{ item.password }}"
      update_password: always
    with_items: "{{ users }}"

